import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from '@contexts/AuthContext';
import { LogOut, Users, Settings } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
export function AdminPanelPage() {
    const { logout, user } = useAuth();
    const navigate = useNavigate();
    const handleLogout = () => {
        logout();
        navigate('/login');
    };
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("header", { className: "bg-white border-b border-gray-200 sticky top-0 z-50", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 py-4 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900", children: "Admin Panel" }), _jsxs("p", { className: "text-sm text-gray-600", children: ["System Administration \u2022 ", user?.name] })] }), _jsxs("button", { onClick: handleLogout, className: "flex items-center gap-2 px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors", children: [_jsx(LogOut, { size: 20 }), "Logout"] })] }) }), _jsxs("main", { className: "max-w-7xl mx-auto p-4", children: [_jsxs("div", { className: "grid grid-cols-1 tablet:grid-cols-2 gap-4", children: [_jsxs("div", { className: "card space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Users, { className: "text-primary-600", size: 28 }), _jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold", children: "User Management" }), _jsx("p", { className: "text-sm text-gray-600", children: "Manage system users and roles" })] })] }), _jsx("button", { className: "btn-primary w-full", children: "Manage Users" })] }), _jsxs("div", { className: "card space-y-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Settings, { className: "text-primary-600", size: 28 }), _jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold", children: "System Settings" }), _jsx("p", { className: "text-sm text-gray-600", children: "Configure system parameters" })] })] }), _jsx("button", { className: "btn-primary w-full", children: "Settings" })] })] }), _jsxs("div", { className: "mt-6 card", children: [_jsx("h2", { className: "text-lg font-semibold mb-4", children: "System Status" }), _jsxs("div", { className: "grid grid-cols-1 tablet:grid-cols-3 gap-4", children: [_jsxs("div", { className: "p-4 bg-success-50 rounded-lg", children: [_jsx("p", { className: "text-sm text-gray-600", children: "Status" }), _jsx("p", { className: "text-2xl font-bold text-success-600", children: "Healthy" })] }), _jsxs("div", { className: "p-4 bg-blue-50 rounded-lg", children: [_jsx("p", { className: "text-sm text-gray-600", children: "API Version" }), _jsx("p", { className: "text-2xl font-bold text-blue-600", children: "v1.0.0" })] }), _jsxs("div", { className: "p-4 bg-gray-50 rounded-lg", children: [_jsx("p", { className: "text-sm text-gray-600", children: "Last Updated" }), _jsx("p", { className: "text-2xl font-bold text-gray-600", children: new Date().toLocaleDateString() })] })] })] })] })] }));
}
